spring:
  profiles:
    active: development-oracl
---
spring:
  profiles: development-oracl
  application:
    name: user-service
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}         #INSTEAD, CAN JUST ADD ENV VARIABLES    SPRING_DATASOURCE_URL/USERNAME/PASSWORD
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 5555
---      
spring:
  profiles: development-h2
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:test 
    username: sa 
    driver-class-name: org.h2.Driver 
  jpa:
    hibernate:
      ddl-auto: validate
  show-sql: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 9001
